miky_admin_settings:
    resource: "@MikySettingsBundle/Resources/config/routing/back.yml"
    prefix : /%miky_admin.admin_key_path%


miky_api_settings:
    resource: "@MikySettingsBundle/Resources/config/routing/api.yml"

